const topics=[
{id:"kindness",image:"assets/kindness-stimulus.jpg",title:"Kindness",icon:"🤝",summary:"Helping others and showing care.",stimulus:"Ways We Show Kindness",actions:["Helping Others","Sharing","Comforting Others","Being Respectful and Polite","Caring for Others","Saying Thank You"],
qa:[
["Why is it important to be kind to others?","I think kindness is important because...","When we are kind...","For example, once...","We should try to...","I think kindness is important because it makes people feel cared for. When we are kind, we can also build better friendships. Once, I shared my stationery with a classmate who forgot his pencil case. We should notice when someone needs help and do small acts of kindness."],
["Tell me about a time when you showed kindness to someone.","One time I showed kindness by...","This helped because...","What happened was...","I think we should...","One time I showed kindness by helping an elderly neighbour. He had difficulty seeing clearly, so I helped him press the lift button. He thanked me and I felt happy that I could help. I think we should look out for people who may need assistance."],
["How can children show more kindness in school?","Children can show kindness by...","This is helpful because...","I have seen this when...","I suggest that pupils...","Children can show kindness by including others and helping classmates who are struggling. This helps everyone feel welcome. I have seen classmates explain difficult work to one another. I suggest that pupils also use kind words and encourage one another."]],
stim:[
["Look at the picture. Which way of showing kindness have you practised before? Tell me about what you did.","From the stimulus, I would choose...","I think this is kind because...","Once, I...","I have practised comforting others when they are feeling upset or distressed. Showing empathy and lending a listening ear lets people know that they are cared for and that they do not have to handle their problems alone. Last term, my seatmate burst into tears after receiving a low mark on her English spelling test. I placed a gentle hand on her shoulder, offered her a piece of tissue, and told her that everyone makes mistakes. I also offered to practise spelling words with her during recess, which brought a smile back to her face. We should always be observant of our friends' body language so we can offer support whenever someone looks sad or lonely.","From the stimulus, I would choose helping an elderly person. I think this is kind because some elderly people may need support. Once, I helped an elderly neighbour press the lift button because he had difficulty seeing clearly. Children can also look out for people who may need help."],
["Why do you think showing kindness to others is important?","The action I would choose is...","It is easy and useful because...","I have done something similar when...","I suggest that children...","In my opinion, showing kindness is crucial because it builds a warm, caring, and harmonious community where everyone feels valued. Kindness is like a chain reaction; when you perform a single good deed, it brightens the other person's day and inspires them to pass that kindness on to someone else. Once, when I lost my pocket money in school and could not buy lunch, a classmate saw me sitting alone and shared half of his sandwich with me. His generosity touched my heart. Since that day, I always look for opportunities to share my snacks with others. We can practise small daily acts of kindness, such as greeting our school cleaners, holding doors open for teachers, or helping peers carry heavy books."],
["How can you show kindness to someone who is having a difficult day?","The stimulus encourages people to...","It is effective because...","It reminds me of a time when...","I think schools can...","I can show kindness by spending time with them, offering encouraging words, or giving them a small thoughtful gesture. Simple acts of care demonstrate genuine concern and help lift a person's mood when they are feeling overwhelmed by difficulties. When my friend's pet cat passed away earlier this year, she was very quiet and withdrawn at school. I wrote her a short card with supportive messages and drew a sweet picture of her cat to cheer her up. We can set up a Kindness Tree in class where students can pin encouraging notes and compliments to uplift anyone having a tough day."]]},
{id:"safety",image:"assets/safety-stimulus.jpg",title:"Safety",icon:"🦺",summary:"Making careful choices and preventing accidents.",stimulus:"Ways We Keep Our School Safe",actions:["Walking Safely","Using Handrails","Keeping Our Classroom Tidy","Being Kind and Respectful","Knowing What to Do in an Emergency"],
qa:[
["Which safety rule is especially important for children? Why?","I think an important safety rule is...","It is important because...","I remember a time when...","Children should...","I think using the pedestrian crossing is especially important. It helps drivers see us clearly. I remember waiting for the green man with my family even when the road looked clear. Children should be patient and follow road safety rules."],
["Tell me about a time when you had to be careful to stay safe.","One time I had to be careful was...","I needed to be careful because...","What happened was...","Next time, I will...","One time I had to be careful near a wet floor. I could have slipped and hurt myself. I slowed down and walked around the wet area. Next time, I will continue to look out for warning signs."],
["What can your school do to help pupils stay safe?","My school can...","This would help because...","At school, I have noticed...","I suggest...","My school can put clear safety signs near stairs and busy corridors. This helps remind pupils to slow down. I have noticed that teacher reminders make pupils more careful. I suggest giving short safety reminders during assembly too."]],
stim:[
["Look at the picture. Which way of keeping the school safe have you practised before? Please share what you have done.","From the stimulus, I think...","This is important because...","I remember a time when...","I have practised using handrails when walking up and down the stairs at school. Holding onto the handrail provides extra support and keeps me steady. This is very important during dismissal or recess when the staircases are crowded with students, as it prevents us from slipping, tripping, or falling. I remember an incident last term when I was walking down the stairs after recess. I was distracted and accidentally misstepped, but because I had a firm grip on the handrail, I managed to catch my balance immediately. If I had not held onto it, I would have tumbled down and hurt my knees or bumped into the student in front of me. We should always walk in twos, keeping to the left side of the stairs and refrain from rushing or playing near the steps.","From the stimulus, I think using a pedestrian crossing is very important. It reduces the risk of road accidents. I remember waiting for the green man with my family. Children should always cross at a safe place and pay attention to traffic."],
["Why do you think it is important for everyone to practise safety rules in school?","I have practised...","It keeps me safe because...","Once, I...","In my opinion, it is extremely important for everyone to follow safety rules so that school remains a secure and happy place for all students to learn. When pupils obey rules, such as walking instead of running along corridors, we prevent painful accidents and serious injuries. Safety is everyone's responsibility, and if one person acts recklessly, it can endanger others. Once, during recess, I saw two boys running wildly across the canteen floor while holding hot noodle bowls. One of them tripped over a school bag on the floor and spilt the hot soup all over himself, burning his arm. It made me realise how dangerous simple carelessness can be. I suggest that student councillors or prefects share short safety reminders during morning assemblies to remind everyone about the rules.","I have practised wearing a helmet when cycling. It keeps me safe because it protects my head if I fall. Once, I almost lost my balance while cycling, and I was glad I had my helmet on. I would remind others to wear protective equipment too."],
["What will you do if you notice a schoolmate not following the safety rules? How will you help to promote safety rules in school?","I think the poster is telling us to...","This message matters because...","It reminds me of...","Schools can also...","If I notice a schoolmate ignoring safety rules, I will approach them calmly and give them a friendly reminder. Sometimes students engage in unsafe behaviour without realising the danger, such as swinging on their chairs or leaving bags in doorways. A polite word can help them correct their actions before an accident happens. Last month, I noticed my classmate leaving her heavy school bag right in the middle of the classroom aisle. I pointed out that someone could trip over it in the dark, so she thanked me and immediately tucked it inside her locker. To promote safety, we can design colourful posters with clear illustrations and slogans to hang in high-traffic areas like the canteen and library."]]},
{id:"respect",title:"Respect",icon:"🙏",summary:"Being polite, considerate and thoughtful.",stimulus:"A poster shows respectful behaviour at school and in the neighbourhood.",actions:["Greeting neighbours politely","Listening when others speak","Queueing patiently","Taking care of shared spaces"],
qa:[
["How do you show respect to the people around you?","I show respect by...","This is respectful because...","For example, I...","We should...","I show respect by greeting adults politely and listening when someone speaks. This shows that I value the other person. For example, I greet my neighbours when I meet them at the lift. We should use polite words and think about other people's feelings."],
["Why is respect important in school?","Respect is important because...","When pupils respect one another...","I have experienced this when...","Pupils should...","Respect is important because pupils need to learn and work together. When pupils respect one another, the classroom is calmer. I experienced this during group work when my teammates listened to everyone's ideas. Pupils should take turns and speak politely."],
["What can you do if you disagree with a friend?","If I disagree with a friend, I can...","This is better because...","Once, my friend and I...","I think we should...","If I disagree with a friend, I can stay calm and listen. This is better because arguing may make the problem worse. Once, my friend and I wanted different games, so we took turns. I think we should explain our ideas politely and find a fair solution."]],
stim:[
["Look at the poster. Which of these ways to show respect do you usually practise at home or in school? Tell me more about it.","From the stimulus, I practise...","This shows respect because...","For example, I...","I usually practise listening to others when they are speaking. Giving someone my full attention shows that I value their thoughts and feelings. It helps build good relationships and prevents misunderstandings or conflicts. During group discussions in class, I make sure to maintain eye contact, keep quiet, and wait for my classmates to finish speaking before I share my thoughts. At home, when my parents are talking to me, I put away my toys or devices to listen carefully to what they have to say. We should practise active listening by nodding along and asking polite follow-up questions instead of interrupting when someone else is talking.","From the stimulus, I practise greeting neighbours politely. This shows respect because it makes people feel acknowledged. For example, I greet my neighbours when I meet them near the lift. People should be friendly and considerate to those around them."],
["Can you share a time when someone showed consideration or respect to you, or when you did so for someone else? How did it make you feel?","I would choose...","It would help because...","I have seen this when...","Our class can...","I remember a time when my classmate showed consideration to me by valuing my opinion during an art project. When someone respects your ideas, it makes you feel appreciated, accepted, and confident to contribute more. Last term, our team was working on a poster design. I was quite shy, but my group leader asked for my thoughts and agreed to use my idea for the background drawing. Her thoughtful action made me feel respected and happy to be part of the team. We should actively invite quieter classmates or younger siblings to share their ideas so everyone feels included and respected."],
["Why do you think it is important for us to show respect to others in public places, like on public transport or in the library? What might happen if people do not show respect?","I think the poster wants us to...","This is important because...","It reminds me of...","Children can...","I think showing respect in public places is important because it ensures that everyone can share common spaces peacefully and comfortably. Public places belong to everyone. If people are respectful, such as keeping noise levels down in the library or offering seats on the MRT, it creates a pleasant environment for all users. Once, while I was reading at the public library, a group of children started talking loudly and running around. It made it very difficult for others to concentrate, and an elderly man had to ask them to quiet down. If people do not show respect, public spaces become chaotic, noisy, and unpleasant. We should always follow the posted rules, speak softly in quiet zones, and give up seats to those who need them more."]]},
{id:"energy",image:"assets/energy-stimulus.jpg",title:"Energy Conservation",icon:"💡",summary:"Saving electricity and avoiding waste.",stimulus:"Ways We Use Energy Wisely",actions:["Switching Off Lights When Not in Use","Not Wasting Water","Using Natural Light and Ventilation","Turning Off Devices When Not in Use","Reusing and Recycling"],
qa:[
["What is one way you save electricity at home?","At home, I save electricity by...","This helps because...","For example, I...","Families can also...","At home, I save electricity by switching off lights and fans when I leave a room. This helps because electricity should not be wasted. For example, I check my bedroom before going to school. Families can also unplug unused chargers."],
["Why should children learn to conserve energy?","Children should learn to conserve energy because...","If we waste energy...","I learnt this when...","Schools can...","Children should learn to conserve energy because our habits affect the environment. If we waste energy, more resources are needed. I learnt this when my teacher reminded us to switch off classroom lights. Schools can teach simple energy-saving habits."],
["What can your class do to use less electricity?","Our class can...","This saves electricity because...","In my classroom, we...","I suggest that...","Our class can switch off lights and fans when they are not needed. This saves electricity in empty rooms. In my classroom, we sometimes use daylight when it is bright enough. I suggest having an energy monitor each week."]],
stim:[
["Look at the picture. Which way of saving energy shown in the picture would you like to practise more often? Why?","From the stimulus, I practise...","This saves energy because...","At home or school, I...","I would like to practise using natural light and ventilation more often during the day. Opening curtains and windows lets in bright sunlight and cool breezes, which allows us to keep electric lights, fans, and air-conditioners switched off to save electricity. Whenever I do my homework on weekend mornings, I open my bedroom blinds fully. The room becomes brightly lit and fresh, so I do not need to turn on my desk lamp or air-conditioner at all until late evening. We can encourage our teacher to open the classroom windows during morning lessons on cool days instead of turning on all the lights and air-conditioning.","From the stimulus, I practise switching off lights. This saves energy because an empty room does not need lighting. At home, I switch off my bedroom light before leaving. Everyone can build this simple habit."],
["Tell me about a time when you made an effort to save energy.","I would encourage my family to...","This would help because...","For example, at home...","I made a deliberate effort to save energy by turning off electrical devices at the main wall socket when they were not in use. Many people do not know that electrical appliances still consume vampire energy when left on standby mode, which wastes power continuously. Last month, I noticed that our family television set and gaming console were left on standby mode overnight with their red lights glowing. I made it my daily bedtime duty to switch off the main power plugs for all appliances in the living room. Everyone should do a quick sweep around their house before going out or sleeping to ensure no unused devices or switches are left on.","I would encourage my family to unplug unused chargers. This would help us avoid unnecessary electricity use. At home, I sometimes notice chargers left plugged in. We could also use natural light during the day."],
["How would you encourage your classmates to develop good energy-saving habits?","The main message is...","This matters because...","It reminds me to...","Schools and families can...","I would encourage my classmates by setting a good example myself and creating simple visual reminders around the classroom. Peer actions are contagious; when classmates see me consistently saving energy, they will be reminded to do the same. During recess last week, I stayed back for a moment to switch off the classroom lights and fans before leaving for the canteen. Seeing this, two of my classmates started checking the light switches whenever our class left for outdoor PE lessons. We can stick small, eye-catching reminder stickers above light switches and water taps that say, Save Energy, Save Our Planet."]]},
{id:"environment",image:"assets/environment-stimulus.jpg",title:"Clean Environment",icon:"🌱",summary:"Keeping shared places clean and pleasant.",stimulus:"Ways We Keep Our Environment Clean",actions:["Throwing Trash Properly","Keeping Our Surroundings Tidy","Planting Trees","Using Reusable Items","Sorting and Recycling","Picking Up Litter","Spreading Awareness"],
qa:[
["What do you do to keep your surroundings clean?","I keep my surroundings clean by...","This is important because...","For example, I...","Everyone can...","I keep my surroundings clean by throwing rubbish into the correct bin and keeping my desk tidy. This is important because a clean place is healthier and more pleasant. For example, I clear food wrappers after recess. Everyone can clean up after themselves."],
["Why is it important to keep public places clean?","It is important because...","Dirty places can...","I once saw...","People should...","It is important to keep public places clean because many people share them. Dirty places can attract pests and make others uncomfortable. I once saw litter left at a food court. People should clear their rubbish and use the bins provided."],
["What can pupils do to make the school cleaner?","Pupils can...","This would help because...","In my school, I have...","I suggest...","Pupils can throw rubbish away properly and keep classrooms tidy. This helps keep the school pleasant. I have seen classmates remind one another to clean their tables. I suggest having short class clean-up routines."]],
stim:[
["Look at the picture. Which of the ways shown in the picture do you practise at home or in school? Tell me about what you do.","From the stimulus, I practise...","This is useful because...","For example, I...","Everyone should...","From the stimulus, I practise throwing rubbish into bins. This is useful because it keeps shared places clean. For example, I clear my wrappers after recess. Everyone should clean up after themselves."],
["Why do you think it is important for everyone to play a part in keeping the environment clean?","I think ... would help most.","It would help because...","At school, I have seen...","Pupils can also...","I think keeping classrooms tidy would help most. It would help because pupils spend many hours in their classrooms. At school, I have seen classmates clean their tables after activities. Pupils can also put rubbish into the correct bins."],
["What do you think the school could do to encourage pupils to keep the school clean?","I think the poster is telling us...","This is important because...","It reminds me of...","We can...","I think the poster is telling us that everyone is responsible for keeping places clean. This is important because public spaces belong to everyone. It reminds me to clear my own rubbish. We can also politely remind friends to do the same."]]}
];



const oralBank={
kindness:{vocab:[["considerate","thinking about other people's feelings"],["thoughtful","showing care for another person"],["comfort","help someone feel better"],["encourage","give someone confidence or hope"],["grateful","feeling thankful"],["lend a helping hand","help someone who needs assistance"],["brighten someone's day","make someone feel happier"],["show appreciation","show that you are thankful"],["caring","kind and concerned about others"],["support","help someone through a difficulty"]],sentences:["I noticed that he needed help, so I offered to help him.","Even a small act of kindness can brighten someone's day.","We should be considerate of other people's feelings.","Sometimes, people just need someone to listen to them.","Helping others makes them feel cared for.","I was glad that I could lend a helping hand.","His kindness made me feel grateful.","We should look out for people who may need our help."],experiences:["Help an elderly neighbour at the lift.","Share stationery with a classmate who forgot something.","Comfort a friend who is upset.","Help someone carry something heavy.","Thank a cleaner, teacher or family member."],idea:"Kindness does not have to be a big action. Think: notice someone → understand what the person needs → help → explain how both of you felt.",example:"Once, I saw an elderly neighbour waiting for the lift. He had difficulty seeing clearly, so I helped him press the lift button. He thanked me and I felt happy that I could lend a helping hand."},
safety:{vocab:[["cautious","careful to avoid danger"],["hazard","something that may cause harm"],["prevent","stop something from happening"],["accident","an unexpected event that causes harm"],["injury","damage or harm to the body"],["handrail","a rail you hold for support"],["emergency","a serious situation needing quick action"],["surroundings","the area around you"],["reckless","not thinking about danger"],["remind","help someone remember something"]],sentences:["Safety is everyone's responsibility.","We should always be aware of our surroundings.","Following safety rules can prevent accidents.","I reminded him politely because I was worried that he might get hurt.","Running along the corridor can be dangerous.","We should not put ourselves or others in danger.","It is always better to be careful.","A simple reminder can prevent a serious accident."],experiences:["Use the handrail when walking on stairs.","Walk instead of running along corridors.","Move a school bag out of the aisle so nobody trips.","Remind a friend about an unsafe action.","Follow the teacher's instructions during a fire drill."],idea:"Think: danger → possible consequence → prevention. Example: bag on floor → someone may trip → move it aside.",example:"Once, I saw my classmate leave his school bag in the middle of the aisle. Someone could have tripped over it, so I reminded him to put it under his desk. He moved it immediately."},
respect:{vocab:[["considerate","thinking about other people's needs"],["polite","showing good manners"],["patient","able to wait calmly"],["appreciate","recognise the value of someone or something"],["interrupt","speak while another person is speaking"],["cooperate","work together willingly"],["give way","allow another person to go first"],["listen attentively","listen carefully with full attention"],["value someone's opinion","show that another person's ideas matter"],["public space","a place shared by everyone"]],sentences:["Showing respect makes other people feel valued.","We may have different opinions, but we should still respect one another.","I listened carefully without interrupting.","We should think about how our actions affect others.","Being respectful helps us get along with one another.","I appreciated what she did for me.","Everyone deserves to be treated with respect.","We should be considerate when using public spaces."],experiences:["Listen while a classmate is speaking.","Accept another person's idea during group work.","Give up a seat on the MRT or bus.","Keep quiet in a library.","Speak politely to parents, teachers and school staff."],idea:"Respect is more than saying please and thank you. It also means listening, giving others space, considering their feelings and accepting different opinions.",example:"During a group discussion, my classmate had a different idea from mine. Instead of interrupting him, I listened carefully. In the end, we combined our ideas and completed the project together."},
energy:{vocab:[["conserve","use carefully so less is wasted"],["electricity","energy used to power lights and devices"],["unnecessary","not needed"],["switch off","turn something off"],["natural light","light from the sun"],["ventilation","fresh air moving through a place"],["standby mode","a low-power mode when a device is not fully off"],["energy-saving","using less energy"],["reduce consumption","use a smaller amount"],["reusable","able to be used many times"]],sentences:["We should avoid wasting electricity unnecessarily.","Small energy-saving habits can make a difference.","I always switch off the lights when I leave the room.","We can use natural light during the daytime.","Electrical devices should be switched off when they are not in use.","Saving energy also helps to protect the environment.","Everyone can play a part in conserving energy.","We should develop good energy-saving habits from young."],experiences:["Switch off classroom lights and fans before recess.","Open curtains instead of switching on lights.","Turn off a computer after using it.","Remind family members not to waste electricity.","Turn off the tap while brushing your teeth."],idea:"Think: action → what it saves → why it matters. Example: switch off lights → save electricity → reduce unnecessary energy use.",example:"Before going for recess, I noticed that the classroom lights and fans were still on. I switched them off because nobody was using the classroom. Since then, I have tried to remember to do this every day."},
environment:{vocab:[["environment","the natural world and places around us"],["surroundings","the area around us"],["litter","rubbish left in the wrong place"],["recycle","process used items so they can be used again"],["reusable","able to be used many times"],["waste","material that is thrown away"],["pollution","harmful or dirty substances in the environment"],["dispose of","get rid of something properly"],["keep tidy","keep a place neat and clean"],["shared responsibility","a duty that belongs to everyone"]],sentences:["Everyone has a part to play in keeping the environment clean.","We should dispose of our rubbish properly.","A clean environment is more pleasant for everyone.","We should not expect cleaners to do everything for us.","Using reusable items can reduce waste.","We can encourage others by setting a good example.","Litter can make our surroundings dirty and unpleasant.","Keeping our environment clean is a shared responsibility."],experiences:["Pick up litter in school.","Clean up after eating.","Recycle paper or plastic.","Use a reusable water bottle.","Help to keep the classroom tidy."],idea:"Think about personal responsibility. Explain what you, other pupils, families and the school can do instead of expecting cleaners to do everything.",example:"After recess, I once saw an empty drink bottle on the floor. I picked it up and put it into the correct recycling bin. Although it was only a small action, I felt that I was doing my part to keep the school clean."}
};

const oralExplanations={
kindness:["Kindness makes people feel cared for and supported.","It can cheer someone up when they are sad or having a difficult day.","Kind actions help us build stronger friendships and trust.","When one person is kind, others may be encouraged to do the same.","A caring community makes people feel safe, welcome and valued."],
safety:["Safety rules help to prevent accidents and injuries.","Careful behaviour protects not only ourselves but also the people around us.","Small unsafe actions can sometimes lead to serious consequences.","Following rules makes busy places such as stairs and corridors safer for everyone.","Friendly reminders can help someone notice a danger before an accident happens."],
respect:["Respect makes other people feel valued and appreciated.","Listening carefully helps to prevent misunderstandings and arguments.","Respect allows people with different opinions to get along peacefully.","Being considerate makes shared and public places pleasant for everyone.","When people feel respected, they are more confident to share their ideas."],
energy:["Saving energy reduces unnecessary use of electricity and resources.","Switching things off when they are not needed prevents waste.","Using natural light can reduce the need for electric lighting during the day.","Good energy-saving habits, when practised every day, can make a difference over time.","Conserving energy is one way we can help protect the environment."],
environment:["Clean surroundings are healthier and more pleasant for everyone.","Putting rubbish in the correct bin helps to prevent litter and pollution.","Reusable items and recycling can reduce the amount of waste we throw away.","Everyone shares public spaces, so keeping them clean is a shared responsibility.","Setting a good example can encourage other people to care for the environment too."]
};

const universalSentences=["I noticed that ___, so I decided to ___.","This is important because ___.","One experience I remember was when ___.","At first, ___, but after that, ___.","This made me realise that ___.","Although it may seem like a small action, ___.","We can encourage others by setting a good example.","Everyone has a part to play in ___."];

const referenceConcepts={
kindness:[
 {state:["comfort","respect","polite","help","share","care","thank"],explain:["care","alone","empathy","support","brighten","kind"],personal:["once","last","when i","neighbour","classmate","friend","school"],suggestion:["should","can","help","support","kind"]},
 {state:["important","kindness","kind"],explain:["community","valued","brighten","inspire","caring","happy","joy"],personal:["once","classmate","friend","school","lunch","money","share"],suggestion:["should","can","greet","help","share"]},
 {state:["spend time","encourag","thoughtful","help","listen","comfort"],explain:["care","concern","mood","overwhelmed","support"],personal:["friend","once","when","school","pet","card"],suggestion:["can","should","encourag","note","compliment"]}
],
safety:[
 {state:["handrail","safe","tidy","walk"],explain:["support","steady","slip","trip","fall","accident"],personal:["once","last","stairs","recess","school"],suggestion:["should","walk","left","rush","play"]},
 {state:["important","safety","rules"],explain:["accident","injur","danger","reckless","safe"],personal:["once","recess","canteen","school","saw"],suggestion:["should","remind","assembly","prefect","councillor"]},
 {state:["remind","calm","friendly","tell"],explain:["danger","unsafe","accident","correct"],personal:["last","classmate","bag","aisle","once"],suggestion:["poster","reminder","slogan","can","promote"]}
],
respect:[
 {state:["listen","respect"],explain:["attention","value","thought","feeling","relationship","misunderstanding"],personal:["class","group","home","parents","when"],suggestion:["listen","nod","question","interrupt","should"]},
 {state:["classmate","respect","consideration","opinion"],explain:["appreciated","accepted","confident","included"],personal:["last","project","group","team","idea"],suggestion:["invite","share","included","respect","should"]},
 {state:["important","respect","public"],explain:["peace","comfort","library","mrt","pleasant"],personal:["once","library","public","children","elderly"],suggestion:["rules","quiet","seat","should","respect"]}
],
energy:[
 {state:["natural light","ventilation","window","curtain"],explain:["sunlight","breeze","electric","light","fan","air-condition"],personal:["homework","weekend","bedroom","morning","when"],suggestion:["teacher","window","classroom","cool","should","can"]},
 {state:["turning off","switch off","socket","device"],explain:["standby","power","waste","energy","electric"],personal:["last","television","gaming","overnight","home"],suggestion:["check","switch","unused","before","should"]},
 {state:["example","reminder","encourage"],explain:["classmate","same","saving energy","remind"],personal:["recess","classroom","lights","fans","classmate"],suggestion:["sticker","switch","tap","save energy","can"]}
]
};

let mode=null,activeTopic=null,qi=0,hintLevel=0,recognition=null,listening=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const home=$("#homeView"),practice=$("#practiceView"),learn=$("#learnView"),chooser=$("#topicChooser"),grid=$("#topicGrid"),stimCard=$("#stimulusCard"),layout=$("#practiceLayout"),transcript=$("#transcript"),coach=$("#coachText"),feedback=$("#feedbackPanel"),steps=$$(".progress-step");

function selectMode(m){mode=m;$$(".mode-card").forEach(x=>x.classList.toggle("selected",x.dataset.mode===m));$("#chosenModeLabel").textContent=m==="qa"?"💬 QUESTIONS & ANSWERS · NO PICTURE":m==="stimulus"?"🖼️ STIMULUS-BASED CONVERSATION · WITH STIMULUS":"📚 LEARN & BUILD · ORAL BANK";chooser.classList.remove("hidden");renderTopics();chooser.scrollIntoView({behavior:"smooth",block:"start"});}
function renderTopics(){grid.innerHTML=topics.map(t=>'<button class="topic-card" data-id="'+t.id+'"><div class="topic-icon">'+t.icon+'</div><h3>'+t.title+'</h3><p>'+t.summary+'</p></button>').join("");grid.querySelectorAll(".topic-card").forEach(b=>b.onclick=()=>mode==="learn"?openLearn(b.dataset.id):openTopic(b.dataset.id));}
function openLearn(id){activeTopic=topics.find(t=>t.id===id);const b=oralBank[id];home.classList.remove("active");practice.classList.remove("active");learn.classList.add("active");$("#learnTopicBadge").textContent=activeTopic.title;$("#learnTitle").textContent=activeTopic.icon+" "+activeTopic.title+" — Build My Oral Bank";$("#learnVocab").innerHTML=b.vocab.map(v=>'<div class="vocab-item"><strong>'+v[0]+'</strong><span>'+v[1]+'</span></div>').join("");$("#learnSentences").innerHTML=b.sentences.map(x=>'<div class="bank-line">“'+x+'”</div>').join("");$("#learnExplanations").innerHTML=oralExplanations[id].map(x=>'<div class="explain-line"><span class="why-badge">WHY</span><span>'+x+'</span></div>').join("");$("#learnExperiences").innerHTML=b.experiences.map(x=>'<div class="experience-line">✓ '+x+'</div>').join("");$("#learnIdea").textContent=b.idea;$("#learnExample").textContent=b.example;$("#universalSentences").innerHTML=universalSentences.map(x=>'<div class="bank-line">“'+x+'”</div>').join("");}
function qObj(){const a=activeTopic[mode][qi];return {q:a[0],starters:{state:a[1],explain:a[2],personal:a[3],suggestion:a[4]},model:a[5]};}
function openTopic(id){activeTopic=topics.find(t=>t.id===id);qi=0;home.classList.remove("active");practice.classList.add("active");renderQuestion();}
function renderQuestion(){const x=qObj();$("#modeBadge").textContent=mode==="qa"?"💬 Q&A · No Picture":"🖼️ Stimulus · With Picture";$("#topicBadge").textContent=activeTopic.title;$("#questionCounter").textContent="Question "+(qi+1)+" of "+activeTopic[mode].length;$("#questionText").textContent=x.q;$("#questionTypeLabel").textContent=mode==="qa"?"QUESTIONS & ANSWERS":"STIMULUS-BASED CONVERSATION";stimCard.classList.toggle("hidden",mode==="qa");layout.classList.toggle("qa-layout",mode==="qa");if(mode==="stimulus"){const img=$("#stimulusImage");if(img){if(activeTopic.image){img.src=activeTopic.image;img.alt=activeTopic.stimulus;img.classList.remove("hidden");$("#stimulusEmoji").classList.add("hidden");}else{img.classList.add("hidden");$("#stimulusEmoji").classList.remove("hidden");$("#stimulusEmoji").textContent=activeTopic.icon;}}$("#stimulusText").textContent=activeTopic.stimulus;$("#stimulusActions").innerHTML=activeTopic.actions.map(a=>'<div class="stimulus-action">'+a+'</div>').join("");coach.textContent="Look carefully at the stimulus first. Choose one detail you can refer to, then answer in your own words.";}else coach.textContent="Listen to the question carefully. Give a direct answer first, then build it with SEPS.";transcript.value="";feedback.classList.add("hidden");hintLevel=0;update({});$("#prevQuestionBtn").disabled=qi===0;$("#nextQuestionBtn").textContent=qi===activeTopic[mode].length-1?"Finish Topic ✓":"Next Question →";}
function analyse(){const raw=transcript.value.trim(),t=raw.toLowerCase(),wc=raw.split(/\s+/).filter(Boolean).length;return {state:wc>=5,explain:/\bbecause\b|this helps|this is important|so that|so /.test(t),personal:/\bonce\b|one day|last |when i|for example|at home|at school|i remember|i have/.test(t),suggestion:/\bshould\b|\bcould\b|\bcan also\b|i suggest|we can|children can|people can|everyone can|next time/.test(t)};}
function update(r){let n=0;["state","explain","personal","suggestion"].forEach((k,i)=>{steps[i].classList.remove("done","active");if(r[k]){steps[i].classList.add("done");n++;}});$("#progressSummary").textContent=n+" / 4";const miss=["state","explain","personal","suggestion"].findIndex(k=>!r[k]);if(Object.keys(r).length&&miss>=0)steps[miss].classList.add("active");}
function hint(step,level=0){const x=qObj(),labels={state:"State",explain:"Explain",personal:"Personal Experience",suggestion:"Suggestion"},needsPicture=mode==="stimulus"&&/look at the (picture|poster)|shown in the picture/i.test(x.q),base={state:needsPicture?["Start by referring to something you see in the stimulus.",'Try: "'+x.starters.state+'"',"Choose one action from the stimulus and give your view."]:["Answer the question directly first.",'Try: "'+x.starters.state+'"',"Say your main idea clearly in one sentence."],explain:["Ask yourself: Why? How does this help?",'Try: "'+x.starters.explain+'"',"Use because and give one clear reason."],personal:["Think of home, school, recess, CCA, your neighbourhood or a family outing.",'Try: "'+x.starters.personal+'"',"Tell who was there, what happened and what you did."],suggestion:["What could someone do next?",'Try: "'+x.starters.suggestion+'"',"Give one practical action."]};coach.textContent=labels[step]+" hint: "+base[step][Math.min(level,2)];steps.forEach(s=>s.classList.remove("active"));steps[["state","explain","personal","suggestion"].indexOf(step)].classList.add("active");}
function guide(){if(!transcript.value.trim()){hint("state",0);return;}const r=analyse();update(r);const refs=referenceConcepts[activeTopic.id]?.[qi];const words=transcript.value.toLowerCase();const matched=refs?Object.entries(refs).filter(([k,terms])=>terms.some(term=>words.includes(term))&&!r[k]).map(([k])=>k):[];matched.forEach(k=>r[k]=true);update(r);const missing=["state","explain","personal","suggestion"].filter(k=>!r[k]);feedback.classList.remove("hidden");if(!missing.length){coach.textContent="Well done. You covered all four SEPS parts. Now say the whole answer again smoothly without looking at the hints.";feedback.innerHTML="<h3>Great job 👏</h3><p class='good'>State ✓ Explain ✓ Personal Experience ✓ Suggestion ✓</p><p>Your answer does not need to copy the reference answer. Keep your own ideas and real experience, then improve clarity and expression.</p>";return;}const k=missing[0],names={state:"State",explain:"Explain",personal:"Personal Experience",suggestion:"Suggestion"};hint(k,0);feedback.innerHTML="<h3>Keep building your answer</h3><p><span class='next'>Next:</span> "+names[k]+". The coach uses the hidden answer sheet as a reference for the important ideas, but will not reveal it yet. Add one or two sentences in your own words, then press <strong>Guide My Answer</strong> again.</p>";}
function parent(){if(!activeTopic){$("#parentContent").innerHTML="<div class='parent-block'><h3>Two separate modes</h3><p><strong>Questions & Answers:</strong> no picture; answer the question directly using SEPS.</p><p><strong>Stimulus-Based Conversation:</strong> look at and refer to the stimulus before expanding with SEPS.</p></div>";}else{const x=qObj();$("#parentContent").innerHTML="<div class='parent-block'><h3>"+(mode==="qa"?"Questions & Answers — No Picture":"Stimulus-Based Conversation — With Stimulus")+"</h3><p>"+x.q+"</p></div><div class='parent-block'><h3>Sentence starters</h3><p><strong>State:</strong> "+x.starters.state+"<br><strong>Explain:</strong> "+x.starters.explain+"<br><strong>Personal Experience:</strong> "+x.starters.personal+"<br><strong>Suggestion:</strong> "+x.starters.suggestion+"</p></div><div class='parent-block'><h3>Reference answer for coaching</h3><p>"+x.model+"</p><p><strong>Use:</strong> Check whether Xiao Wei covers the important meaning. Do not require him to copy this wording or invent a personal experience.</p></div>";}$("#parentDialog").showModal();}
function speech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("#speakBtn").textContent="⌨️ Type Answer";$("#speakBtn").onclick=()=>transcript.focus();return;}recognition=new SR();recognition.lang="en-SG";recognition.interimResults=true;recognition.continuous=true;recognition.onstart=()=>{listening=true;$("#listeningStatus").textContent="Listening…";$("#speakBtn").textContent="⏹ Stop Speaking";};recognition.onresult=e=>{let f="",i="";for(let n=e.resultIndex;n<e.results.length;n++){if(e.results[n].isFinal)f+=e.results[n][0].transcript+" ";else i+=e.results[n][0].transcript;}if(f)transcript.value=(transcript.value+" "+f).trim();$("#listeningStatus").textContent=i?"Listening: "+i:"Listening…";};recognition.onend=()=>{listening=false;$("#listeningStatus").textContent="";$("#speakBtn").textContent="🎤 Start Speaking";};recognition.onerror=()=>recognition.stop();$("#speakBtn").onclick=()=>listening?recognition.stop():recognition.start();}
$$(".mode-card").forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));$("#learnBackBtn").onclick=()=>{learn.classList.remove("active");home.classList.add("active");activeTopic=null;};$("#learnQaBtn").onclick=()=>{learn.classList.remove("active");mode="qa";practice.classList.add("active");qi=0;renderQuestion();};$("#learnStimBtn").onclick=()=>{learn.classList.remove("active");mode="stimulus";practice.classList.add("active");qi=0;renderQuestion();};$("#changeModeBtn").onclick=()=>{chooser.classList.add("hidden");$$(".mode-card").forEach(x=>x.classList.remove("selected"));mode=null;};$("#backBtn").onclick=()=>{if(listening)recognition.stop();practice.classList.remove("active");home.classList.add("active");activeTopic=null;};$("#checkBtn").onclick=guide;$("#stuckBtn").onclick=()=>{const r=transcript.value.trim()?analyse():{};const k=["state","explain","personal","suggestion"].find(x=>!r[x])||"state";hint(k,hintLevel);hintLevel=Math.min(2,hintLevel+1);};$("#clearBtn").onclick=()=>{transcript.value="";feedback.classList.add("hidden");hintLevel=0;update({});coach.textContent=mode==="stimulus"?"Look at the stimulus again, then start with one detail you can see.":"Start again with a direct answer to the question.";};$("#prevQuestionBtn").onclick=()=>{if(qi>0){qi--;renderQuestion();}};$("#nextQuestionBtn").onclick=()=>{if(qi<activeTopic[mode].length-1){qi++;renderQuestion();}else{coach.textContent="Topic complete! Great practice. Go back to Topics when you are ready for another one.";feedback.classList.remove("hidden");feedback.innerHTML="<h3>Topic complete ⭐</h3><p>Try this topic again on another day with fewer hints.</p>";}};$("#parentModeBtn").onclick=parent;steps.forEach((b,i)=>b.onclick=()=>hint(["state","explain","personal","suggestion"][i],1));speech();