const topics=[
{id:"kindness",title:"Kindness",icon:"🤝",summary:"Helping others and showing care.",stimulus:"Ways We Show Kindness",actions:["Helping Others","Sharing","Comforting Others","Being Respectful and Polite","Caring for Others","Saying Thank You"],
qa:[
["Why is it important to be kind to others?","I think kindness is important because...","When we are kind...","For example, once...","We should try to...","I think kindness is important because it makes people feel cared for. When we are kind, we can also build better friendships. Once, I shared my stationery with a classmate who forgot his pencil case. We should notice when someone needs help and do small acts of kindness."],
["Tell me about a time when you showed kindness to someone.","One time I showed kindness by...","This helped because...","What happened was...","I think we should...","One time I showed kindness by helping an elderly neighbour. He had difficulty seeing clearly, so I helped him press the lift button. He thanked me and I felt happy that I could help. I think we should look out for people who may need assistance."],
["How can children show more kindness in school?","Children can show kindness by...","This is helpful because...","I have seen this when...","I suggest that pupils...","Children can show kindness by including others and helping classmates who are struggling. This helps everyone feel welcome. I have seen classmates explain difficult work to one another. I suggest that pupils also use kind words and encourage one another."]],
stim:[
["Look at the picture. Which way of showing kindness have you practised before? Tell me about what you did.","From the stimulus, I would choose...","I think this is kind because...","Once, I...","Children can also...","From the stimulus, I would choose helping an elderly person. I think this is kind because some elderly people may need support. Once, I helped an elderly neighbour press the lift button because he had difficulty seeing clearly. Children can also look out for people who may need help."],
["Why do you think showing kindness to others is important?","The action I would choose is...","It is easy and useful because...","I have done something similar when...","I suggest that children...","The action I would choose is sharing with a classmate. It is easy because children have many chances to help one another at school. I once lent a pencil to a classmate who forgot his pencil case. I suggest that children notice small ways to help every day."],
["How can you show kindness to someone who is having a difficult day?","The stimulus encourages people to...","It is effective because...","It reminds me of a time when...","I think schools can...","The stimulus encourages people to help others through simple actions. It is effective because the examples are easy to understand and practise. It reminds me of a time when I helped a classmate. I think schools can display similar reminders and encourage pupils to care for others."]]},
{id:"safety",title:"Safety",icon:"🦺",summary:"Making careful choices and preventing accidents.",stimulus:"Ways We Keep Our School Safe",actions:["Walking Safely","Using Handrails","Keeping Our Classroom Tidy","Being Kind and Respectful","Knowing What to Do in an Emergency"],
qa:[
["Which safety rule is especially important for children? Why?","I think an important safety rule is...","It is important because...","I remember a time when...","Children should...","I think using the pedestrian crossing is especially important. It helps drivers see us clearly. I remember waiting for the green man with my family even when the road looked clear. Children should be patient and follow road safety rules."],
["Tell me about a time when you had to be careful to stay safe.","One time I had to be careful was...","I needed to be careful because...","What happened was...","Next time, I will...","One time I had to be careful near a wet floor. I could have slipped and hurt myself. I slowed down and walked around the wet area. Next time, I will continue to look out for warning signs."],
["What can your school do to help pupils stay safe?","My school can...","This would help because...","At school, I have noticed...","I suggest...","My school can put clear safety signs near stairs and busy corridors. This helps remind pupils to slow down. I have noticed that teacher reminders make pupils more careful. I suggest giving short safety reminders during assembly too."]],
stim:[
["Look at the picture. Which way of keeping the school safe have you practised before? Please share what you have done.","From the stimulus, I think...","This is important because...","I remember a time when...","Children should...","From the stimulus, I think using a pedestrian crossing is very important. It reduces the risk of road accidents. I remember waiting for the green man with my family. Children should always cross at a safe place and pay attention to traffic."],
["Why do you think it is important for everyone to practise safety rules in school?","I have practised...","It keeps me safe because...","Once, I...","I would remind others to...","I have practised wearing a helmet when cycling. It keeps me safe because it protects my head if I fall. Once, I almost lost my balance while cycling, and I was glad I had my helmet on. I would remind others to wear protective equipment too."],
["What will you do if you notice a schoolmate not following the safety rules? How will you help to promote safety rules in school?","I think the poster is telling us to...","This message matters because...","It reminds me of...","Schools can also...","I think the poster is telling us to think before we act and follow safety rules. This matters because accidents can happen quickly. It reminds me to be careful at school and on the road. Schools can also use demonstrations to teach safe behaviour."]]},
{id:"respect",title:"Respect",icon:"🙏",summary:"Being polite, considerate and thoughtful.",stimulus:"A poster shows respectful behaviour at school and in the neighbourhood.",actions:["Greeting neighbours politely","Listening when others speak","Queueing patiently","Taking care of shared spaces"],
qa:[
["How do you show respect to the people around you?","I show respect by...","This is respectful because...","For example, I...","We should...","I show respect by greeting adults politely and listening when someone speaks. This shows that I value the other person. For example, I greet my neighbours when I meet them at the lift. We should use polite words and think about other people's feelings."],
["Why is respect important in school?","Respect is important because...","When pupils respect one another...","I have experienced this when...","Pupils should...","Respect is important because pupils need to learn and work together. When pupils respect one another, the classroom is calmer. I experienced this during group work when my teammates listened to everyone's ideas. Pupils should take turns and speak politely."],
["What can you do if you disagree with a friend?","If I disagree with a friend, I can...","This is better because...","Once, my friend and I...","I think we should...","If I disagree with a friend, I can stay calm and listen. This is better because arguing may make the problem worse. Once, my friend and I wanted different games, so we took turns. I think we should explain our ideas politely and find a fair solution."]],
stim:[
["Look at the poster. Which of these ways to show respect do you usually practise at home or in school? Tell me more about it.","From the stimulus, I practise...","This shows respect because...","For example, I...","People should...","From the stimulus, I practise greeting neighbours politely. This shows respect because it makes people feel acknowledged. For example, I greet my neighbours when I meet them near the lift. People should be friendly and considerate to those around them."],
["Can you share a time when someone showed consideration or respect to you, or when you did so for someone else? How did it make you feel?","I would choose...","It would help because...","I have seen this when...","Our class can...","I would choose listening when others speak. It would help because everyone gets a chance to share ideas. I have seen this during group work when classmates listen carefully. Our class can practise taking turns and not interrupting."],
["Why do you think it is important for us to show respect to others in public places, like on public transport or in the library? What might happen if people do not show respect?","I think the poster wants us to...","This is important because...","It reminds me of...","Children can...","I think the poster wants us to treat others politely and thoughtfully. This is important because everyone deserves respect. It reminds me to listen carefully when others speak. Children can practise respect through small actions every day."]]},
{id:"energy",title:"Energy Conservation",icon:"💡",summary:"Saving electricity and avoiding waste.",stimulus:"Ways We Use Energy Wisely",actions:["Switching Off Lights When Not in Use","Not Wasting Water","Using Natural Light and Ventilation","Turning Off Devices When Not in Use","Reusing and Recycling"],
qa:[
["What is one way you save electricity at home?","At home, I save electricity by...","This helps because...","For example, I...","Families can also...","At home, I save electricity by switching off lights and fans when I leave a room. This helps because electricity should not be wasted. For example, I check my bedroom before going to school. Families can also unplug unused chargers."],
["Why should children learn to conserve energy?","Children should learn to conserve energy because...","If we waste energy...","I learnt this when...","Schools can...","Children should learn to conserve energy because our habits affect the environment. If we waste energy, more resources are needed. I learnt this when my teacher reminded us to switch off classroom lights. Schools can teach simple energy-saving habits."],
["What can your class do to use less electricity?","Our class can...","This saves electricity because...","In my classroom, we...","I suggest that...","Our class can switch off lights and fans when they are not needed. This saves electricity in empty rooms. In my classroom, we sometimes use daylight when it is bright enough. I suggest having an energy monitor each week."]],
stim:[
["Look at the picture. Which way of saving energy shown in the picture would you like to practise more often? Why?","From the stimulus, I practise...","This saves energy because...","At home or school, I...","Everyone can...","From the stimulus, I practise switching off lights. This saves energy because an empty room does not need lighting. At home, I switch off my bedroom light before leaving. Everyone can build this simple habit."],
["Tell me about a time when you made an effort to save energy.","I would encourage my family to...","This would help because...","For example, at home...","We could also...","I would encourage my family to unplug unused chargers. This would help us avoid unnecessary electricity use. At home, I sometimes notice chargers left plugged in. We could also use natural light during the day."],
["How would you encourage your classmates to develop good energy-saving habits?","The main message is...","This matters because...","It reminds me to...","Schools and families can...","The main message is that everyone can save energy through small actions. This matters because many small habits can reduce waste. It reminds me to switch things off when I do not need them. Schools and families can remind children to practise these habits."]]},
{id:"environment",title:"Clean Environment",icon:"🌱",summary:"Keeping shared places clean and pleasant.",stimulus:"Ways We Keep Our Environment Clean",actions:["Throwing Trash Properly","Keeping Our Surroundings Tidy","Planting Trees","Using Reusable Items","Sorting and Recycling","Picking Up Litter","Spreading Awareness"],
qa:[
["What do you do to keep your surroundings clean?","I keep my surroundings clean by...","This is important because...","For example, I...","Everyone can...","I keep my surroundings clean by throwing rubbish into the correct bin and keeping my desk tidy. This is important because a clean place is healthier and more pleasant. For example, I clear food wrappers after recess. Everyone can clean up after themselves."],
["Why is it important to keep public places clean?","It is important because...","Dirty places can...","I once saw...","People should...","It is important to keep public places clean because many people share them. Dirty places can attract pests and make others uncomfortable. I once saw litter left at a food court. People should clear their rubbish and use the bins provided."],
["What can pupils do to make the school cleaner?","Pupils can...","This would help because...","In my school, I have...","I suggest...","Pupils can throw rubbish away properly and keep classrooms tidy. This helps keep the school pleasant. I have seen classmates remind one another to clean their tables. I suggest having short class clean-up routines."]],
stim:[
["Look at the picture. Which of the ways shown in the picture do you practise at home or in school? Tell me about what you do.","From the stimulus, I practise...","This is useful because...","For example, I...","Everyone should...","From the stimulus, I practise throwing rubbish into bins. This is useful because it keeps shared places clean. For example, I clear my wrappers after recess. Everyone should clean up after themselves."],
["Why do you think it is important for everyone to play a part in keeping the environment clean?","I think ... would help most.","It would help because...","At school, I have seen...","Pupils can also...","I think keeping classrooms tidy would help most. It would help because pupils spend many hours in their classrooms. At school, I have seen classmates clean their tables after activities. Pupils can also put rubbish into the correct bins."],
["What do you think the school could do to encourage pupils to keep the school clean?","I think the poster is telling us...","This is important because...","It reminds me of...","We can...","I think the poster is telling us that everyone is responsible for keeping places clean. This is important because public spaces belong to everyone. It reminds me to clear my own rubbish. We can also politely remind friends to do the same."]]}
];

let mode=null,activeTopic=null,qi=0,hintLevel=0,recognition=null,listening=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const home=$("#homeView"),practice=$("#practiceView"),chooser=$("#topicChooser"),grid=$("#topicGrid"),stimCard=$("#stimulusCard"),layout=$("#practiceLayout"),transcript=$("#transcript"),coach=$("#coachText"),feedback=$("#feedbackPanel"),steps=$$(".progress-step");

function selectMode(m){mode=m;$$(".mode-card").forEach(x=>x.classList.toggle("selected",x.dataset.mode===m));$("#chosenModeLabel").textContent=m==="qa"?"💬 QUESTIONS & ANSWERS · NO PICTURE":"🖼️ STIMULUS-BASED CONVERSATION · WITH STIMULUS";chooser.classList.remove("hidden");renderTopics();chooser.scrollIntoView({behavior:"smooth",block:"start"});}
function renderTopics(){grid.innerHTML=topics.map(t=>'<button class="topic-card" data-id="'+t.id+'"><div class="topic-icon">'+t.icon+'</div><h3>'+t.title+'</h3><p>'+t.summary+'</p></button>').join("");grid.querySelectorAll(".topic-card").forEach(b=>b.onclick=()=>openTopic(b.dataset.id));}
function qObj(){const a=activeTopic[mode][qi];return {q:a[0],starters:{state:a[1],explain:a[2],personal:a[3],suggestion:a[4]},model:a[5]};}
function openTopic(id){activeTopic=topics.find(t=>t.id===id);qi=0;home.classList.remove("active");practice.classList.add("active");renderQuestion();}
function renderQuestion(){const x=qObj();$("#modeBadge").textContent=mode==="qa"?"💬 Q&A · No Picture":"🖼️ Stimulus · With Picture";$("#topicBadge").textContent=activeTopic.title;$("#questionCounter").textContent="Question "+(qi+1)+" of "+activeTopic[mode].length;$("#questionText").textContent=x.q;$("#questionTypeLabel").textContent=mode==="qa"?"QUESTIONS & ANSWERS":"STIMULUS-BASED CONVERSATION";stimCard.classList.toggle("hidden",mode==="qa");layout.classList.toggle("qa-layout",mode==="qa");if(mode==="stimulus"){$("#stimulusEmoji").textContent=activeTopic.icon;$("#stimulusText").textContent=activeTopic.stimulus;$("#stimulusActions").innerHTML=activeTopic.actions.map(a=>'<div class="stimulus-action">'+a+'</div>').join("");coach.textContent="Look carefully at the stimulus first. Choose one detail you can refer to, then answer in your own words.";}else coach.textContent="Listen to the question carefully. Give a direct answer first, then build it with SEPS.";transcript.value="";feedback.classList.add("hidden");hintLevel=0;update({});$("#prevQuestionBtn").disabled=qi===0;$("#nextQuestionBtn").textContent=qi===activeTopic[mode].length-1?"Finish Topic ✓":"Next Question →";}
function analyse(){const raw=transcript.value.trim(),t=raw.toLowerCase(),wc=raw.split(/\s+/).filter(Boolean).length;return {state:wc>=5,explain:/\bbecause\b|this helps|this is important|so that|so /.test(t),personal:/\bonce\b|one day|last |when i|for example|at home|at school|i remember|i have/.test(t),suggestion:/\bshould\b|\bcould\b|\bcan also\b|i suggest|we can|children can|people can|everyone can|next time/.test(t)};}
function update(r){let n=0;["state","explain","personal","suggestion"].forEach((k,i)=>{steps[i].classList.remove("done","active");if(r[k]){steps[i].classList.add("done");n++;}});$("#progressSummary").textContent=n+" / 4";const miss=["state","explain","personal","suggestion"].findIndex(k=>!r[k]);if(Object.keys(r).length&&miss>=0)steps[miss].classList.add("active");}
function hint(step,level=0){const x=qObj(),labels={state:"State",explain:"Explain",personal:"Personal Experience",suggestion:"Suggestion"},needsPicture=mode==="stimulus"&&/look at the (picture|poster)|shown in the picture/i.test(x.q),base={state:needsPicture?["Start by referring to something you see in the stimulus.",'Try: “'+x.starters.state+'”',"Choose one action from the stimulus and give your view."]:["Answer the question directly first.",'Try: “'+x.starters.state+'”',"Give your own clear opinion in one sentence."]:["Answer the question directly first.",'Try: “'+x.starters.state+'”',"Say your main idea clearly in one sentence."],explain:["Ask yourself: Why? How does this help?",'Try: “'+x.starters.explain+'”',"Use because and give one clear reason."],personal:["Think of home, school, recess, CCA, your neighbourhood or a family outing.",'Try: “'+x.starters.personal+'”',"Tell who was there, what happened and what you did."],suggestion:["What could someone do next?",'Try: “'+x.starters.suggestion+'”',"Give one practical action."]};coach.textContent=labels[step]+" hint: "+base[step][Math.min(level,2)];steps.forEach(s=>s.classList.remove("active"));steps[["state","explain","personal","suggestion"].indexOf(step)].classList.add("active");}
function guide(){if(!transcript.value.trim()){hint("state",0);return;}const r=analyse();update(r);const missing=["state","explain","personal","suggestion"].filter(k=>!r[k]);feedback.classList.remove("hidden");if(!missing.length){coach.textContent="Well done. You covered all four SEPS parts. Now say the whole answer again smoothly without looking at the hints.";feedback.innerHTML="<h3>Great job 👏</h3><p class='good'>State ✓ Explain ✓ Personal Experience ✓ Suggestion ✓</p><p>Your answer does not need to copy the reference answer. Keep your own ideas and real experience, then improve clarity and expression.</p>";return;}const k=missing[0],names={state:"State",explain:"Explain",personal:"Personal Experience",suggestion:"Suggestion"};hint(k,0);feedback.innerHTML="<h3>Keep building your answer</h3><p><span class='next'>Next:</span> "+names[k]+". The coach uses the hidden answer sheet as a reference for the important ideas, but will not reveal it yet. Add one or two sentences in your own words, then press <strong>Guide My Answer</strong> again.</p>";}
function parent(){if(!activeTopic){$("#parentContent").innerHTML="<div class='parent-block'><h3>Two separate modes</h3><p><strong>Questions & Answers:</strong> no picture; answer the question directly using SEPS.</p><p><strong>Stimulus-Based Conversation:</strong> look at and refer to the stimulus before expanding with SEPS.</p></div>";}else{const x=qObj();$("#parentContent").innerHTML="<div class='parent-block'><h3>"+(mode==="qa"?"Questions & Answers — No Picture":"Stimulus-Based Conversation — With Stimulus")+"</h3><p>"+x.q+"</p></div><div class='parent-block'><h3>Sentence starters</h3><p><strong>State:</strong> "+x.starters.state+"<br><strong>Explain:</strong> "+x.starters.explain+"<br><strong>Personal Experience:</strong> "+x.starters.personal+"<br><strong>Suggestion:</strong> "+x.starters.suggestion+"</p></div><div class='parent-block'><h3>Reference answer for coaching</h3><p>"+x.model+"</p><p><strong>Use:</strong> Check whether Xiao Wei covers the important meaning. Do not require him to copy this wording or invent a personal experience.</p></div>";}$("#parentDialog").showModal();}
function speech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("#speakBtn").textContent="⌨️ Type Answer";$("#speakBtn").onclick=()=>transcript.focus();return;}recognition=new SR();recognition.lang="en-SG";recognition.interimResults=true;recognition.continuous=true;recognition.onstart=()=>{listening=true;$("#listeningStatus").textContent="Listening…";$("#speakBtn").textContent="⏹ Stop Speaking";};recognition.onresult=e=>{let f="",i="";for(let n=e.resultIndex;n<e.results.length;n++){if(e.results[n].isFinal)f+=e.results[n][0].transcript+" ";else i+=e.results[n][0].transcript;}if(f)transcript.value=(transcript.value+" "+f).trim();$("#listeningStatus").textContent=i?"Listening: "+i:"Listening…";};recognition.onend=()=>{listening=false;$("#listeningStatus").textContent="";$("#speakBtn").textContent="🎤 Start Speaking";};recognition.onerror=()=>recognition.stop();$("#speakBtn").onclick=()=>listening?recognition.stop():recognition.start();}
$$(".mode-card").forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));$("#changeModeBtn").onclick=()=>{chooser.classList.add("hidden");$$(".mode-card").forEach(x=>x.classList.remove("selected"));mode=null;};$("#backBtn").onclick=()=>{if(listening)recognition.stop();practice.classList.remove("active");home.classList.add("active");activeTopic=null;};$("#checkBtn").onclick=guide;$("#stuckBtn").onclick=()=>{const r=transcript.value.trim()?analyse():{};const k=["state","explain","personal","suggestion"].find(x=>!r[x])||"state";hint(k,hintLevel);hintLevel=Math.min(2,hintLevel+1);};$("#clearBtn").onclick=()=>{transcript.value="";feedback.classList.add("hidden");hintLevel=0;update({});coach.textContent=mode==="stimulus"?"Look at the stimulus again, then start with one detail you can see.":"Start again with a direct answer to the question.";};$("#prevQuestionBtn").onclick=()=>{if(qi>0){qi--;renderQuestion();}};$("#nextQuestionBtn").onclick=()=>{if(qi<activeTopic[mode].length-1){qi++;renderQuestion();}else{coach.textContent="Topic complete! Great practice. Go back to Topics when you are ready for another one.";feedback.classList.remove("hidden");feedback.innerHTML="<h3>Topic complete ⭐</h3><p>Try this topic again on another day with fewer hints.</p>";}};$("#parentModeBtn").onclick=parent;steps.forEach((b,i)=>b.onclick=()=>hint(["state","explain","personal","suggestion"][i],1));speech();